### ISSUE TITLE
Translating CSRF Helper error notices

### ISSUE THREAD

**Issue by valokammi** [modmore/CSRFHelper#3]
Is there a way to translate error messages. They seem included in snippets, not in lexicons.
I know that they are very rare. Last time when I saw error notice was when I installed ReCaptcha V2 and first time I test form it gives error (not happened every modx installation that I tested). Resend of form was success. Maybe caching issue (all csrf helper needed things are uncached in form)?
No errors in error log.
Modx 2.7.2 @linux
CSRFHelper 1.0.0
Formit 4.2.3
ReCaptchaV2 3.2.1 Beta

**Comment by Mark-H** [comment]
Added in 1.1, you can now tweak it via the lexicon management interface:

![Schermafbeelding 2022-04-14 om 01 10 20](https://user-images.githubusercontent.com/312944/163285897-d20551b9-f171-4b5d-ba21-0f6ce2fbfb7d.jpg)
